project:
  type: website
  output-dir: docs
  resources: 
    - "library"

website:
  title: "Machine_vision: coffee grading"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: code.qmd
        text: Coding

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

